#!/bin/bash

if [[ -z "$1" ]]; then
  >&2 echo "Error: no GitHub URL pointing to a vim plugin repo was specified"
  exit 1
fi

if ! [[ $1 =~ git@github.com:*/* ]]; then
  >&2 echo "Error: the URL given does not look like a correct GitHub repo URL"
  exit 1
fi

GITURL=$1
GITNAME=$(echo "$GITURL" | cut -d':' -f2)
REPONAME=$(echo "$GITNAME" | cut -d'/' -f2)

git submodule add $GITURL .vim/bundle/$REPONAME
git commit -m "added vim plugin $GITNAME"
