#!/bin/bash

if [[ -z "$1" ]]; then
  >&2 echo Usage: $0 \<submodule name\>
  exit 1
fi

MATCH=$(cat .gitmodules | grep "^\[submodule \".vim/bundle/$1\"\]$")

if [[ -z $MATCH ]]; then
  >&2 echo Nothing found for submodule \"$1\"
  exit 1
fi

SUBMODULE=".vim/bundle/$1"

git rm $SUBMODULE
git commit -m "removed submodule $SUBMODULE"

